# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule:
    - cron: '0,15,30,45 * * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get the latest data
        run: |
           mkdir -p ./result
           touch ./result/index.json
           curl -L -X GET 'https://script.google.com/macros/s/AKfycby0xdKkzfXovdxmGOUOBGwptupdxReW5JoY4RyuckoB4KFgm8nY4w23hIuBZBc49nuX/exec?action=all' > ./result/index.json

      - name: Push artifact to gh-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.4.1
        with:
          build_dir: result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
